fix: add standalone msvc notice
cpredef/predef pull request #32
Opened 2023-07-31 16:52 UTC by trainstopperd

According to the [Microsoft documentation](https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170), the compiler is actually the one defining some of the architecture macros, and not Visual Studio itself. I have added an extra part to the macros that are referenced in the above link to signify that they are *also* defined by MSVC standalone, rather than just Visual Studio. 

To make it clear, I have not changed *every* occurrence of a claim that Visual Studio defines the macro, only the ones that were referenced in the documentation above. I was a bit confused by it myself, so I figured it wouldn't be an awful idea to potentially clear up confusion. If there is a better way to signify this, however, please do let me know and I will happily make the changes.

2023-07-31 17:39 UTC, a1batross commented
I don't think there should be any difference in predefined variables of MSVC running within Visual Studio and standalone build tools. In the end, it's the same cl.exe binary.

I also think that Visual Studio already implies MSVC, as by default you cannot use Visual Studio IDE with any other compiler.

Can you show the example where compiler behavior is different in IDE environment and with build-tools? Except Intellisense, as it uses completely different frontend for code analyze, though it probably could be mentioned somewhere.

2023-07-31 18:29 UTC, trainstopperd commented
I'm not aware of any place where build tools differ from the actual compiler. I just found myself personally confused by it, figuring it was Visual Studio telling MSVC to define the macros rather than them being built into the compiler, so I thought I would try and clear up potential confusion in others by making the distinction.

2023-07-31 18:54 UTC, breese commented
The predef pages has always used "Visual Studio" as a synonym for MS(V)C. If we were to use another name then I would prefer "Visual C++" or "Microsoft Visual C++" over an abbreviation.

2023-07-31 18:59 UTC, trainstopperd commented
I'm cool with expanding the abbreviation like that as long as everyone is onboard with making *a* change in the first place. 🙂

2023-08-01 14:11 UTC, a1batross commented
For better clarification, all `Visual Studio` mentions could be replaced just by `Visual C++` indicating that the provided information is for compiler rather than IDE.

@breese what do you think of this?

2023-08-01 15:30 UTC, breese commented
I am fine with that change. It is consistent with the name used on the Compilers list.

2023-08-01 18:33 UTC, trainstopperd commented
Awesome. I'll make these changes once I get home from work. Presumably, it would look something like `Defined by Visual C++`, rather than `Defined by Visual Studio`, just so we're all on the same page. 🙂

2023-08-02 09:27 UTC, a1batross commented
Cool, thank you!

2023-08-04 03:07 UTC, trainstopperd commented
Hey everyone, apologies for the delay. Got a bit side tracked. 🙂

Anyway, got the commit through. Let me know if there are any further problems that any of you see.

2023-08-04 03:17 UTC, a1batross requested changes
There are few more Visual Studio mentions in OperatingSystems.md and in example code in VersionNormalization.md. And unneeded `standalone MSVC` mention in Architectures.md.

Other than that, I'm fine with the changes.

2023-08-04 03:17 UTC, a1batross commented on Architectures.md
> +Identification|`_M_IX86`| |Only defined for 32-bits architectures<br/><br/>Defined by Visual C++, standalone MSVC Intel C/C++, Digital Mars, and Watcom C/C++
Stray `standalone MSVC` here.

2023-08-04 03:34 UTC, trainstopperd commented on Architectures.md
> +Identification|`_M_IX86`| |Only defined for 32-bits architectures<br/><br/>Defined by Visual C++, standalone MSVC Intel C/C++, Digital Mars, and Watcom C/C++
Alright, changed.

2023-08-04 03:41 UTC, a1batross approved these changes

2023-08-04 15:09 UTC, merged